// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: livekit_agent.proto

package livekit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_StartAgentJob_FullMethodName = "/livekit.AgentService/StartAgentJob"
	AgentService_StopAgentJob_FullMethodName  = "/livekit.AgentService/StopAgentJob"
	AgentService_ListAgentJobs_FullMethodName = "/livekit.AgentService/ListAgentJobs"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	StartAgentJob(ctx context.Context, in *StartAgentJobRequest, opts ...grpc.CallOption) (*Job, error)
	StopAgentJob(ctx context.Context, in *StopAgentJobRequest, opts ...grpc.CallOption) (*Job, error)
	ListAgentJobs(ctx context.Context, in *ListAgentJobsRequest, opts ...grpc.CallOption) (*ListAgentJobsResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StartAgentJob(ctx context.Context, in *StartAgentJobRequest, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, AgentService_StartAgentJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopAgentJob(ctx context.Context, in *StopAgentJobRequest, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, AgentService_StopAgentJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgentJobs(ctx context.Context, in *ListAgentJobsRequest, opts ...grpc.CallOption) (*ListAgentJobsResponse, error) {
	out := new(ListAgentJobsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	StartAgentJob(context.Context, *StartAgentJobRequest) (*Job, error)
	StopAgentJob(context.Context, *StopAgentJobRequest) (*Job, error)
	ListAgentJobs(context.Context, *ListAgentJobsRequest) (*ListAgentJobsResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) StartAgentJob(context.Context, *StartAgentJobRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAgentJob not implemented")
}
func (UnimplementedAgentServiceServer) StopAgentJob(context.Context, *StopAgentJobRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAgentJob not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentJobs(context.Context, *ListAgentJobsRequest) (*ListAgentJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentJobs not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StartAgentJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartAgentJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartAgentJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartAgentJob(ctx, req.(*StartAgentJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopAgentJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopAgentJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopAgentJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopAgentJob(ctx, req.(*StopAgentJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgentJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentJobs(ctx, req.(*ListAgentJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livekit.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAgentJob",
			Handler:    _AgentService_StartAgentJob_Handler,
		},
		{
			MethodName: "StopAgentJob",
			Handler:    _AgentService_StopAgentJob_Handler,
		},
		{
			MethodName: "ListAgentJobs",
			Handler:    _AgentService_ListAgentJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livekit_agent.proto",
}
